### ISSUE TITLE
Fit mattress protectors

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#102]
need to solve lee cloth issue first
who: CORC
timing: July

**Comment by DeeTaylor87** [comment]
Quotes have been organised for Wednesday 9th July. Dee is meeting suppliers at Quays to discuss requirements. They have promised that they can complete the job by 1st September.

**Comment by DeeTaylor87** [comment]
Quotes should be in by end of week

**Comment by DeeTaylor87** [comment]
I'm particularly interested to see what the quote for weathermax material looks like. This is a really interesting new textile. http://www.safetycomponents.com/WeatherMAX/#WeatherMax

**Comment by DeeTaylor87** [comment]
Protectors have been ordered. They should arrive in the next week or so.

**Comment by DeeTaylor87** [comment]
Beautiful Mattress Protectors have been fitted. They are machine washable and can be tumble dried on a low setting.   Karl from Eco Bedding has done a wonderful job.  Need to test wash them at some time and if they work well as washable covers, consider getting a second set so that we have a spare while the first set is being cleaned.
