### ISSUE TITLE
Install light in engine bay

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#125]

**Comment by DeeTaylor87** [comment]
Communication with BME 28th August
Hi Daniel, Jack Hayden CORC here. The matters we wanted to address are: Light in the engine bay, provision of fuse kit, check the battery monitor, check the electrical cable on the forward keel bolt, Isolation transformer is noisy, Provision of 12V and 240V circuit diagrams

**Comment by DeeTaylor87** [comment]
This item is being done by Chris from BME today. 1st September, 2017

**Comment by DeeTaylor87** [comment]
Beautiful new engine light has been installed in the engine bay.  It is an LED string just above the companionway entrance to the engine bay. It is operated by a magnetic switch just on the starboard side of the LEDs. The magnetic switch is great because it will not be affected by corrosion the way normal switches can be.  It is off in a central position. Slide switch to port for white light. Slide switch to starboard for red light. You might find that sometimes the switch will seem off when it is not quite central - just because the magnet switch can be a little like that - operating via magnet rather than physical contact feels a little different than old fashioned switches.  Just move it a little until the desired effect is achieved.
