### ISSUE TITLE
SOP for main sail management

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#141]

**Comment by DeeTaylor87** [comment]
![batton tensioner and exit](https://user-images.githubusercontent.com/30706096/29923102-9be09de6-8e9b-11e7-9082-fbae3f1cde24.jpg)  This is the tensioner but is also the way you take the battons out of the sail.  Undo the small screw then slide out the grey slide cover so that the batton can be easily removed.
![battons do not go in this end](https://user-images.githubusercontent.com/30706096/29923123-ac8da1fc-8e9b-11e7-82f5-b78bc6b0dc2e.jpg)  Don't be fooled - this is NOT the way to remove battons!

**Comment by DeeTaylor87** [comment]
I contacted Elvstrom Sails today in Perth. 0437 057 589
The fellow there was very helpful.  As background, Elvstrom sails have been made in France for many years but have been bought out by a Danish (I think) company in the last few weeks. The batton receptacles are probably Elvstrom and he is happy to help us source them if we would like to have that information for future reference.  

In regards to the bottom two connections between the sail and the cars, he said the cringles that have been put in have most likely been installed by local sailmakers so contact Bavaria to see who did that work if needed.  He said that sometimes cringles are used because the outhaul can sometimes put substantial strain on that part of the sail if it is pulled too tight. The cringle then becomes a stronger point to help withstand that load.  Sometimes the sailmakers use a piece of dyneema lashed a few times through the cringle joining to the car.  He suggested that the sailmakers may have chosen to use shockchord in that position to allow a bit more give and provide a point where the shockchord can break instead of jamming up the car and pulling all the outhaul load through the car.  It should be clear that the outhaul is too tight because a crease will develop up from the clew.  When dropping the main, always be careful to release the outhaul first so that the main can drop freely.  He said a common error is to try to drop the main while the outhaul is pulling the bottom of the sail and jamming the bottom cars up in the slide.  @peterottesen
