### ISSUE TITLE
SOP for toilet operation — black water tank operation and sink operation

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#147]

**Comment by DeeTaylor87** [comment]
https://www.jamestowndistributors.com/userportal/document.do?docId=769
http://www.sparesmarine.co.uk/_webedit/uploaded-files/All%20Files/Product_Pdfs/Jabsco%2029090-3%20%26%2029120-3%20Toilet.pdf
http://missygoesboating.com/the-best-toilet-paper-for-you-boat/
https://www.whitworths.com.au/main_itemdetail.asp?cat=133&item=89575&intAbsolutePage=
https://www.practical-sailor.com/issues/37_70/features/Best-Marine-Toilet-Papers_12091-1.html
http://uk.boats.com/how-to/how-to-fix-your-marine-toilet/#.WYwMnlEjHIU
http://www.sailnet.com/forums/gear-maintenance/77630-gravity-holding-tank-does-not-drain.html
See the comment made on 6.8.07 at the bottom of this forum http://www.ybw.com/forums/showthread.php?132127-bavaria-holding-tank-problem

**Comment by DeeTaylor87** [comment]
Gulper Pump service information for shower pumps
http://www.whalepumps.com/marine/product.aspx?Category_ID=10020&Product_ID=10039&FriendlyID=Gulley-IC

**Comment by DeeTaylor87** [comment]
When this one is written, we need to be mindful that the waste water pipe in the forward toilet is a little confusing.  The cock is situated just above a 90 degree bend in the pipe so it has frequently been mistaken as 'off' when it is in fact on.  Needs careful instruction so that this mistake is not made again.

**Comment by DeeTaylor87** [comment]
The waste cocks in the aft heads are easy to see when they are off.  When they are OFF you can see them poking up as soon as you open the vanity door. 
![starboard aft head waste off](https://user-images.githubusercontent.com/30706096/30043023-7e44f1e2-9238-11e7-93fc-365c49776f71.jpg)
![port aft head waste off](https://user-images.githubusercontent.com/30706096/30043024-7e77241e-9238-11e7-9887-ca6273f5f384.jpg)

The waste cock in the forward head is much harder to see because it is a little dark in there.  It is OFF when you push it down.

**Comment by DeeTaylor87** [comment]
Need to ensure that our SOPs include ensuring that toilet paper bought for the BAVARIA is easily biodegradable. I just checked COLES brand toilet paper and after well over 3 hours it was still intact in water.  We should NOT buy COLES brand toilet paper.

**Comment by DeeTaylor87** [comment]
Draft is complete and has been sent to committee.
