### ISSUE TITLE
Relabel all switches which have “0/1” with “ON / OFF” positions

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#159]

**Comment by DeeTaylor87** [comment]
I have this on my list of things to look at on Wednesday.   Please let me know if there is a particular supplier I should speak to about this. In the absence of any further info, I'll contact Stripes.
The signage needed for the boat includes the following issues:
Sign stuff needing doing
159 – Easy to read On Off labels needed on all bow thruster and engine cock because the current 0 I labels are too small to read – check on the boat how many and what size we want
158 – Rego and call sign next to radio and in cockpit  
136 – Relabel clutches in cockpit - Two up-haul should be labelled main halyard and topping lift, main->main sheet
131 – position of fire extinguisher in cockpit
117- label the anchor circuit breaker behind cushion below switch panel
116 - Diagram of switch matrix needs to be laminated and placed near switch panel
69 - Turn off gas at bottle sign or sticker

**Comment by smr547** [comment]
I'll Assign each of these to you.

**Comment by DeeTaylor87** [comment]
Done and dusted
