### ISSUE TITLE
Replace dirty saloon cushion covers

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#187]
A number of members (and their spouses) have commented on the poor state of the cushions in the saloon area. One suggestion is to  buy a new set of cushion covers while this design is still current with Barvaria. The colour should be darker.  The new set could be used while the existing set is being cleaned -- and vice/versa.

**Comment by DeeTaylor87** [comment]
Yes - I think it is a great idea and judging by the way the current ones
are wearing, it is definitely needed!   Can we check if Bavaria have them
and confirm that they can actually be removed (when Jack and I tried to
remove one we found it was glued in along a plastic support structure that
was inserted into a deep groove in the cushion). Since Jack has been the
person who has been liaising with Bavaria, and since he understands the
issue, perhaps it would be best for him to have that conversation with
them? I got an upholsterer to estimate the cost of new covers and the price
ranged from about $5000 to $9000 with the upper end being for leather. I do
wonder what Bavaria would charge for both options. I think we are better
off with leather if the club can manage it - scotch guarding is just not up
to the rigours of sea life methinks. But at least having another set would
mean we have an option to extend the life of the current cushions.  I'll
see if I can find some old sheets to make an impromptu cover in the
meantime.

**Comment by jphayden** [comment]
I will ask Kate to  chase up supply and price for new saloon cushion covers

Regards 

Jack

**Comment by DeeTaylor87** [comment]
I checked with Karl, the upholsterer, when he visited to measure for Lee sheets.  The covers are definitely glued in - that is what creates the slightly moulded shape of the seat cushions around the table. They must be cleaned in situ.  I asked him for a quote for washable covers, although we both understood it was a quote for research purposes.

**Comment by DeeTaylor87** [comment]
Quote received from Karl at Eco Marine. @jphayden - how did you go with Kate?

**Comment by jphayden** [comment]
I asked Kate some time ago - .Today she advised that she is chasing Andy for a response

**Comment by smr547** [comment]
This remains and issue. Many people have commented on the need for new (and more durable) cushion covers

**Comment by smr547** [comment]
The maintenance subcommittee discussed this issue

* all agreed that replacement of the covers were desirable
* cost is a factor
* Sam noted that cleaning might be worth trying (he knows a person that can work magic)
* Bill recommended ``Ultra Leather`` as the preferred material
* Dimitri offered to get a quote for new covers
* Possibly get a quote from a supplier at Airlie??
* Will keep this issue open

**Comment by smr547** [comment]
@peterottesen has heard that NZ sailors are having cushion work done in Fiji where the labour rates are low and the workmanship very good. He suggests that, perhaps, we can buy the material in Oz and have new covers made in Fiji during the current cruise. I'll ask Peter to investigate further.

**Comment by smr547** [comment]
@mrmrmartin has organised a supplier to do the work at Boatworks this year. Michael, please advise supplier details and pricing for inclusion in Github / scope of works

@peterottesen @pcbaston @pjwain

**Comment by smr547** [comment]
latest quote attached 
[Michael Martin QU1053.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/12798215/Michael.Martin.QU1053.pdf)

**Comment by smr547** [comment]
New cushions installed

![IMG_4285](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/187884b4-2cc3-40f9-8a70-6f5e28a7b636)
![IMG_4286](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/751cd201-19d9-49e1-982f-f3746606f11c)
![IMG_4288](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/0041c1be-92fa-42ed-9a88-8dccd9d1107b)
![IMG_4287](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/514a4725-03e2-49e5-a2ea-2f3c0b2c78af)

**Comment by pjwain** [comment]
They look beautiful.
