### ISSUE TITLE
Liferaft - mounting of new liferaft

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#237]
Replaces issue #39 -- 8 man liferaft to be exchanged for current 10 man liferaft. Liferaft to be mounted forward of the mast under / or associated with the dinghy.

**Comment by jphayden** [comment]
I have been advised that an 8 PERSON (steven??)  liftefaft  will be available to swap next Tuesday (next week ) Will confirm this progressively as RFD have not been very reliable.

**Comment by jphayden** [comment]
The Life raft Saga (Or - the interesting process of dealing with Survitec)
OK so they were going to do the swap on Tuesday , then it was Friday, Then it turned out they, again, did not have an 8 person raft. They are arriving by boat at the end of this month (they say)
Anyway, I negotiated a loaner - and as they did not have an 8 person liferaft, I got a six person and a four person life raft.
They were delivered today to my place in Berry and the plan is to get them to BB in time for Steven's Trip.
I have not seen them yet as I am in Hospital with a fibrillation problem  - its under control , so I am fine - just doing some tests..

Standby for the next liferaft installment

**Comment by jphayden** [comment]
These are the 6 person and 4 person loaner liferafts - I have them.

![img_1942](https://user-images.githubusercontent.com/30738269/31363994-e98adb2a-adad-11e7-995b-360de9b5e53a.JPG)

**Comment by DaveHolt** [comment]
For info: our liferaft is a Crewsaver 8 person with > 24 hour pack
It measures about:
81-82cm x 55cm x 38-40cms. The rounded canister makes it hard to measure exactly.
According to websites it is likely to weigh from 62-70Kg. 
It looks like the less than 24 hour 8 person equivalent raft weighs about 52Kg.

**Comment by smr547** [comment]
Closing this item -- historical

**Comment by smr547** [comment]
The liferaft may need to be serviced? Check at Boatworks?

**Comment by smr547** [comment]
Closing old issue
