### ISSUE TITLE
Swim platform faulty - does not move

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#251]
When lowering the beach you need to bump it with your shoulder at least three times to shift it. It seems to get stuck.

**Comment by DeeTaylor87** [comment]
I have found that when you haven't lowered it for a while (a day or so), it just doesn't move for a while despite pressing the button. It really does take some time for it to get moving and when it does start moving, it moves in a very jerky fashion. Eventually it starts to work smoothly again. If you raise or lower it within a few hours of that first attempt it works perfectly well. Then when you leave it for an extended period, it starts the whole slow process again. It has been like that since we took possession of the boat. It just took a little while for it to show up because the training days meant that it was being raised and lowered pretty regularly.

**Comment by DaveHolt** [comment]
Swim platform is now stuck half way up/down. PhilK is trying to diagnose it. I told him you can raise it with a rope on a winch. I don't know how to lower it.

**Comment by delcosta** [comment]
Andy need to fix this and we should seek a manual over ride sho we don't have the sticking problem

**Comment by DaveHolt** [comment]
Ensign provided a new printed circuit board. Angus the electrician fitted the board and a limiting switch. Works well now but according to Angus, due to the design still needs a shoulder nudge to get it moving downwards.
