### ISSUE TITLE
Spiral corrosion on mast stays

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#297]
There appears to be  corrosion on the mast stays. The problem may be related to earth leakage most likely from the winch.
![98A5AA50-3E73-4DFF-8800-9D86FD369533](https://user-images.githubusercontent.com/32588100/115673951-86f8c300-a390-11eb-8b69-dd5705e9d34d.jpeg)

**Comment by smr547** [comment]
The rigger and marine electrician need to look at this. I'll organise during the working bee.

@delcosta will be interested

**Comment by smr547** [comment]
Hello Mario,

Nice to talk to you this morning. Could you please do the following work on
Namadgi 3 -- she is at Holmeport Marina (berth C18) for the rest of this
week


   1. Rigging check
   2. Assess spiral corrosion developing in shrouds
   3. Replace dyneema straps on swim platform -- they are wearing out and
   may fail
   4. Please leave the old straps on board, we will keep them as spares


Namadgi will be in use this Saturday (8/5) and is due to sail to
Queenland on Tuesday 11 May.

Invoice to be sent to Peter Wain (cc on this email) as per normal
arrangement with CORC.

kind regards
Steven

-- 
*Steven Ring*
m: +61 417 495 268

**Comment by smr547** [comment]
Annual rigging inspection completed today by Mario Ruel -- [see report](https://drive.google.com/drive/folders/10bM2VFNSnfgT_4E4dYzrF4PXxdH3Cu2O?usp=sharing)

Mario commented that the rig was sound and that the corrosion was "minor and normal". Committee informed of survey result.

Closing this issue
