### ISSUE TITLE
Toilet maceration required when sailing in Queensland waters

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#303]
Apparently, Queensland law requires marine toilet contents to be macerated before discharge to sea (does anyone have a document reference for this?). We believe heavy fines might be imposed if we a caught with no maceration capability. 

This issue is listed for discussion. The key question is: What work needs to be done before Namadgi 3 sets sail for Queensland?

@delcosta @PSARN @peterottesen @pjwain will be interested

**Comment by smr547** [comment]
Several design options are currently under consideration each involving the installation of a macerator either at the pan or between the holding tank and the sea.

Steve Vicni of Pittwater marine made the following points in a conversation I had with him today:

1. Electric toilets can be very effective for maceration at the pan
2. They can be noisy 
3. Maceration at the pan has significant advantages in preventing blockages
4. Installation of a below-tank macerator would be very difficult -- there is not much room under the sinks on Namadgi 3
5. Best to keep one toilet fully manual pump in case of electrical failure
6. He recommends re-installing macerating pumps at the bowl of the other two toilets
7. Experiment with that configuration and see how it goes
8. Be prepared to exchange el

ectric macerator with manual pump and any time during a cruise

If we have one or two operational macerators we can hold our hands on our hearts and avoid any complications with Queensland authorities

@delcosta @PSARN @peterottesen @pjwain will be interested

**Comment by delcosta** [comment]
Steve
I agree with re-installing, but check impellers are OK.

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

**Comment by peterottesen** [comment]
FYI.  It is complicated.  We are not a 'declared ship’.  Quensland water are out to 3 nm.
Untreated sewage

The Great Barrier Reef Marine Park Regulations 1983 <http://www.comlaw.gov.au/Series/F1996B01950> requirements for vessels that hold untreated sewage are:
All fixed toilets on vessels need to be fitted with a macerator to reduce the sewage into a fine slurry so as to be sparsely visible and speed up the breakdown of the waste in the receiving environment. Most electric toilets contain macerators or they can be purchased separately.
If you carry 16 or more people on your boat you will need to store your sewage and may discharge it at least 1 nautical mile or 1.852 km seawards from the nearest reef, island, mainland or an aquaculture facility.
If you carry 15 or less people on your boat, you may discharge untreated sewage in the Marine Park if you are outside of a boat harbour or marina or more than 1 nautical mile or 1.852 km from an aquaculture facility.
Maritime Safety Queensland has introduced nil discharge requirements for untreated sewage in Queensland waters.
Nil discharge waters for untreated sewage for all ships (other than a declared ship).  
The nil discharge waters for untreated sewage (that is, the waters where the discharge of untreated sewage is illegal) from a ship (other than a declared ship) are as follows:

prohibited discharge waters
smooth waters
Hervey Bay waters and northern Moreton Bay waters within 1852 metres (or one nautical mile) of any of the following:
a person in the water
aquaculture fisheries resource
a reef
the mean low water mark of an island or the mainland.
Open waters:
within 926 metres (½ nautical mile) of a wharf or a jetty other than a jetty that is a marina, or
within 1852 metres (1 nautical mile) of:
a person in the water
aquaculture fisheries resources
if a ship has 7 to 15 persons on-board – within 1852 metres (one nautical mile) of any of the following:
a reef
the mean low water mark of an island or the mainland.
 Maritime Safety Queensland website <http://www.msq.qld.gov.au/>.






On 27 Apr 2021, at 10:27 am, Steven Ring ***@***.***> wrote:


Apparently, Queensland law requires marine toilet contents to be macerated before discharge to sea (does anyone have a document reference for this?). We believe heavy fines might be imposed if we a caught with no maceration capability.

This issue is listed for discussion. The key question is: What work needs to be done before Namadgi 3 sets sail for Queensland?

@delcosta <https://github.com/delcosta> @PSARN <https://github.com/PSARN> @peterottesen <https://github.com/peterottesen> @pjwain <https://github.com/pjwain> will be interested

**Comment by delcosta** [comment]
Thanks Peter
This is useful info. It looks like all of out toilets must be macerated.
A well thought out solution needs to be considered.
In the meantime we need to re-install the electric WC’s and make sure they work properly and instructions for use are clear

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

**Comment by smr547** [comment]
Two electrical macerator pumps found on board -- deep in stern lazarette locker, towards stern on stb side. With note originally written by Bill Leslie on packaging

``
Both units will not draw water into bowl. Pumps removed and manual pumps refitted
On installation found that joker valves and hose to tank both fouled with calcium. Why wasn't this rectified on upon fitment of these units?
``

All very good questions. We will proceed with re-installation once we've consulted with Bill.

@delcosta will be interested

**Comment by delcosta** [comment]
Steven
I would say that the units were installed by and electrician and decalcifying ‘not his job’
With decalcification there hopefully will work well

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

**Comment by smr547** [comment]
Bill Leslie has reinstalled two electric toilets in the aft head. The forward head is still manual. Several issues remain.

* the electric pumps are VERY noisy
* they are particularly susceptible to blockage 
* may be unreliable in the longer term
* We may be in breach of Qld law in relation to the forward heads 

Some things to consider:

1. No doubt we need an improved SOP in relation to the toilet operation 
2. Peter's excellent research into Qld law should be turned into a short plain English statement that applies to N3
3. And put up on the CORC website
3. Spare manual toilets (fully serviced) are stowed on board ready to replace a failed electric pump
4. Practical suggestions to comply with law include a) place a lock on the holding tank discharge sea cock  and b) use the toilet for number ones only

These considerations need to be conveyed to all delivery and cruising skippers -- perhaps via Notice to Skippers?

@bullswool @peterottesen @delcosta @PSARN and @pjwain have made valuable contributions to this effort. I'll leave this an open issue for now.

**Comment by smr547** [comment]
@peterottesen reports that the delivery crew have now re-fitted the manual toilet pumps to both aft heads. All heads are now functional but are manual.

**Comment by smr547** [comment]
Unable to fit macerating electric toilets owing to loss of prime with these units. see #383 
Another solution will have to be found

**Comment by smr547** [comment]
Departing Queensland waters -- closing this issue
