### ISSUE TITLE
Install Lee sheets

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#40]
Shane Beashell - Trimmer
who: (will be difficullt as cushions run the wrong way ie athwart ship
timing: July
estimate: $750

**Comment by DeeTaylor87** [comment]
Quotes have been organised for Wednesday 9th August. Shane Beashell's company was contacted but I was told they don't do Lee Sheets. They recommended another supplier and he will quote. He has promised that it can be complete by 1st Sept. Getting quotes from three suppliers.

**Comment by DeeTaylor87** [comment]
Found these online at a good price.  What do people think?
https://www.deckhardware.com.au/bunk-net

**Comment by smr547** [comment]
Great work Dee -- I'll bring this to the attention of the Committee

**Comment by DeeTaylor87** [comment]
Letter sent to Top Quay Trimmers 7th August 2017

Hi Emma,

By now I imagine that Namadgi is back in her berth at Quays. Could you please have a look so that you can quote for us to have lee cloths fitted for the two aft cabins and the saloon couch.  A separate price for each of the forward berths would be great as well.

Also, we will need mattress protectors on all mattresses. We imagine that the aft cabins will have two mattress protectors per cabin so that the split down the middle of the mattresses can be maintained which should provide a strong anchor point for the aft lee cloths.

There is some concern about the type of fabric used on the lee cloths and mattress protectors, so could you please explain which type of fabric is being used in the quotes.

The lee cloth design preferred would be something along these lines: http://www.sailrite.com/How-to-Make-Lee-Cloths-Video
If you are quoting something different, or think it needs improving, enlarging or it is appropriate to change the design to fit the design constraints of the boat, please advise us.

In addition, the syndicate needs to install Jackstays along the length of the boat so that we can secure our harnesses during passages.  Is that something that your company usually looks after? I am wondering how much that would cost and if it would be okay to use dyneema for that purpose?  Perhaps you could quote for jackstays as well?

Thanks for all your help and advice so far,

Dee Taylor

**Comment by DeeTaylor87** [comment]
Note Cat One Requirement

3.16.2 | Bunks shall be   suitable for use at sea. Fixed bunks shall be fitted with lee cloths or   restraints where necessary (not normally required for pipe-cots).
-- | --

**Comment by DeeTaylor87** [comment]
Three quotes due by end of week

**Comment by smr547** [comment]
@peterottesen inspected the yacht with Garth Brice and I on the weekend. We believe that a short length of spectra or similar be mounted near the ceiling aft of the toilet door support by strong points either side of the cabin ceiling. The forward strap form the lee cloth would be attached to this line providing the required support. No grab rail is necessary. I have provided Dee with some photographs of the attachment points.

Other attachment points as described by Dee (aft cabin bulkhead, centre mattress and forward end below mattress) are suitable.

We should go ahead with the quotation specifying this arrangement.

**Comment by DeeTaylor87** [comment]
Order made with Eco Marine Bedding.  Karl will meet us at 10:00am on Saturday during the working bee (26th August) to discuss / finalise attachment points.
@jphayden

**Comment by smr547** [comment]
Well done Dee -- Many thanks. [Here are some photos](https://goo.gl/photos/wJhpY7n7ZrFPoPSUA). @peterottesen  is seen pointing out the attachment points for the strop that will act as the anchor for the forward cord of the Lee sheet in each of the aft cabins. Regards Steven

**Comment by DeeTaylor87** [comment]
Lee Sheets are in.  They look beautiful. :)
