### ISSUE TITLE
Install 3rd reef on mainsail, lines and sheaves in boom

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#47]
Rigger and sailmaker
estimate: $1,000

**Comment by smr547** [comment]
@peterottesen will be interested in this one! :D

**Comment by jphayden** [comment]
Hi Steven - saw that we added the sails label . Is anyone organising a quote for this . I know that the torn sailbag also comes into play here

**Comment by smr547** [comment]
@peterottesen to contact Mario to get a quote. @SimonRD and Paul Jones may have other contacts

**Comment by smr547** [comment]
message from @peterottesen (who is having computer problems)

I have spoken to sailmaker (hoods) and rigger (mario) about the 3rd reef. Hood can do but will take a week. We have to deliver the sail, with battens removed.  Mario will check the boat before Friday and advise on a solution for the boom and deck hardware. I told him the boat goes on a mooring this Friday. He thinks there should not be a problem and knows we want this done by 8 September.  He recommends we use the boom topping lift and fit a Cunningham tackle from the base of the mast to the tack.

I asked him about jack stays. He says the Whitworth product we have identified is the best solution and he can provide at the same cost. He says it has good features. He will also confirm that it is cat 1 compliant.

**Comment by DeeTaylor87** [comment]
Sail is off.  Will be dropped at sail-maker tomorrow.

**Comment by DaveHolt** [comment]
I think I agree with most of Mario's suggestions. Can we afford all of this work now? Are they all high priority? Having only sailed the boat for 2 hours I don't know enough to comment on the idea of dropping back to a single mainsheet. However, if we don't go to a single, at least temporarily, setting the 3rd reef might mean manually hauling and cleating the 3rd reef luff line to a cleat on the mast? I think? I've been doing that for the last 7 weeks so It seems Ok. @mrmrmartin, @peterottesen, @smr547

**Comment by DeeTaylor87** [comment]
Dave, are you saying that we already have a third reef on the sail?

**Comment by DeeTaylor87** [comment]
Sorry - I gather you mean on the boat you are on

**Comment by jphayden** [comment]
Dave and others 
Agree with Dave's comments. Re double mainsheet - it is part of the Bavaria design and is also used on other boats We would have to check on the warranty provisions if we wanted to change as indeed we should with some other of Mario's proposals.
I also think the double mainsheet system works well - but have not been in a blow.
I have arranged with Bill to go up Sunday night so we can be on the boat on Monday and hopefully go through this (if Mario is available) and also the liferaft and dinghy mounting proposals from the Quays.
I also plan to show Andy from Bavaria the sailbag problem and also go through Mario's proposals

**Comment by DeeTaylor87** [comment]
@jphayden I'll see you there Monday too because the lee sheets are being fitted then. Karl was coming over here today but there's a traffic incident and he can't get through. We've arranged Monday instead. The cringle, reef points and cunningham cringle for the 3rd reef should be ready by Tuesday morning at the Sail Maker

**Comment by jphayden** [comment]
I have arranged for Mario to come at "lunchtime"  (tradie talk for afternoon), Can we get a berth number please Dee

**Comment by peterottesen** [comment]
In response to Dave, the basic proposal is to have a Cunningham tackle attached the base of the mast and use this for the third reef. So yes, someone has to go forward and fix to the lowered mainsail at the reefing cringle and jam cleat it. Sailmaker and rigger agreed on this.

**Comment by DeeTaylor87** [comment]
The Berth Number is A36  at RPAYC.  It is booked in my name until the 10th September

**Comment by DeeTaylor87** [comment]
Just found these on the internet - they look similar to the slides that are on the Bavaria for the main sail.
![image](https://user-images.githubusercontent.com/30706096/30000779-20977840-90bb-11e7-81f8-710e5f4076b4.png)
It would be good to know what brand and model ours are - I will check on it when we put up the sail again.

**Comment by DeeTaylor87** [comment]
Hood Sails Website 
http://www.hoodaustralia.com.au/

**Comment by DeeTaylor87** [comment]
Meeting with Mario 4th September
Bill, Jack, Dee met this morning. Recommend we act on the proposal as follows:
**Boom pin is not opened so could fall out** - Bill took care of it

-          **Main sheet block is being damaged by out haul so leads need revising  (See Deck layout la**bour) This is the issue of the blocks at the mast base needing to be repositioned. Reposition as recommended 
-          **Genoa must have a luff extension NOW! $110**  Act on this

-          **Lazy jacks could damage spreaders , they need modifying putting load on the mast and diverting through the spreaders** Act on this

Suggestions for work proposed by Peter
-          **Move main topper to already existing cleat on mast use clutch for aft end of 3rd reef  (See Deck layout labour)**   Act on this one.

-          **You have 2 seperate main sheets both leading to cockpit and only giving 2;1 purchase on each, suggest singling  it to give one more clutch for 3rd reef forward / cunningham  and increase purchase to 4;1  (See Deck layout labour)** 
We would like to run the current system for a little while longer and get feedback in various weather conditions. Mario is recommending this change because he says the current arrangement is placing unneccesary strain on the main sheet at the clutch.  He advises the change primarily because it will involve less wear on the mainsheet and he does not believe there is any advantage in the system as it stands because both sheets are operated at the companionway so there is redundancy in the current system.  Moving it back to a single mainsheet will free up one of the clutches for other operations. We would like to hear some more discussion and seek the committee's recommendation on this one.

       -  **also suggest fitting a black mesh rope bag to store jib halyard and main topping lift under the boom and give one more clutch for the yellow halyard on port side of mast to be lead back to cockpit  (See Deck layout labour)**  Asking for comment - is it worth trying this one to see if it is any better than hanging the ropes on the mast?

Mario also suggested that since the genoa halyard has a clutch at the mast, we don't need it on the jammer at the cockpit.   That frees the jammer for the potential Code 1.   This means that we also free up the xts clutch that we currently have the blue downwind halyard on for the second Third Reef line that we will need if we are going to operate the Third Reef from the cockpit.
@peterottesen please give us a reply from the committee!
Please comment and committee make an official call on this because we need to give Mario the go ahead to start on Wednesday.  @smr547 @peterottesen @DaveHolt @mrmrmartin @delcosta @pjwain @bullswool @jphayden

**Comment by mrmrmartin** [comment]
I agree with all the recommendations they make sense to me.

I do find it interesting that there is a weight load problem with the lazy jacks perhaps we should inform Bavaria/Ensign about this issue.

I agree that we should hold off on changing the main sail sheet until we get advice from other members and check with Bavaria/Ensign to ensure there are no warranty issues.

Did Mario have any ideas about the sail bag in regards to how it is fitted and the problem with it fowling the reefing lines?


cheers

________________________________

**Comment by DeeTaylor87** [comment]
Mario is coming to the boat on Wednesday to begin work.

**Comment by jphayden** [comment]
Agree with Michael - should inform Bavaria (a few things there)

**Comment by jphayden** [comment]
Hi Peter and Simon,
I think you are both up-to-date with our meeting with Mario yesterday. I told him we wanted to go ahead and that I would confirm by email which I am about to do , We had a positive response from the committee members in regard to his proposals. Except for changing  the mainsheet system.  Simon has kindly volunteered to be on board on Wednesday when  Mario would start, so I think Simon would give Mario the final brief,(Simon says) One issue is whether we lead  the forward third reefing line (cringle line) back to the cockpit.
Could Peter  and Simon liaise as to the final set up so that Simon can give the final brief to Mario on Wednesday morning.  Mario  also proposed a black mesh bag on the boom which I don't think got  popular support.
Dee is pushing to get the sail back (Hood a bit tardy ) and maybe Mario can help getting it back on (he would charge of course)

**Comment by DeeTaylor87** [comment]
The sail is back on.  Thanks Simon and Greg. Mario due at the boat today some time to follow up with the deck work.

**Comment by DeeTaylor87** [comment]
Mario attended Namadgi 3 today and tied the number one and two reefs in.  He showed me how to take the reef line through the cringle and back down the other side of the sail to the boom. Tie the reef line aft of the cringle and wrap once around the boom before tying a bowline to secure it to the boom.  Note that the rope should not produce a u shape around itself because if it do so, it risks chafing and breaking. The bowline should be tied on the opposite side of the boom/sail from the side the line entered the cringle for that reef.  Copy the existing pattern for the first and second reef line to ensure it is tied correctly.

The reef line is not attached at the mast end of the sail because it is rarely used and if we tie it up there now, it will flap around under ordinary conditions, causing wear and annoying noise.  When we think we might use the third reef, we take the cunningham (which is a red dyneema line at the base of the mast) from the little grey button loop at the base of the mast and thread it through the third reef cringle when we are setting our first reef.  That cunningham line, then becomes our third reef line until we feel it is no longer immediately needed, when we switch it back to the cunningham.
![cunningham soft shackle 1](https://user-images.githubusercontent.com/30706096/30202565-32a22a98-94c2-11e7-9dd7-2698b27d9064.jpg)
![cunningham soft shackle 2](https://user-images.githubusercontent.com/30706096/30202577-3fc8e5fe-94c2-11e7-9310-bd924cd26acd.jpg)
![third reef line](https://user-images.githubusercontent.com/30706096/30202592-4ac00c58-94c2-11e7-848d-4def6a03747e.jpg)
He also put a protection line at the mast. The idea for this is so that when we are tacking, the genoa sheets will rub on this line (instead of the main electrical cables at the base of the mast).  Eventually the constant chafing will cut this protection line and we can replace it so that it does not end up chafing our electrical cables. 
![protector for electricals at mast](https://user-images.githubusercontent.com/30706096/30202680-9a1a4444-94c2-11e7-8b69-e5c451572408.jpg)

**Comment by DeeTaylor87** [comment]
Mario will return tomorrow to relabel the clutches as needed and hopefully show a few fellas what he has done. @peterottesen @jphayden @mrmrmartin @bullswool

**Comment by DeeTaylor87** [comment]
Can this issue be closed? The work has been done. @peterottesen @DaveHolt @delcosta ?

**Comment by jphayden** [comment]
Not quite Garth had a query Steven may comment
