### ISSUE TITLE
Paint on porthole trim is failing 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#504]
Corrosion is causing the paint to peel -- all fixed porthole on topsides

@pjwain @peterottesen @PSARN will be interested
![n3_porthole_paint](https://user-images.githubusercontent.com/4327895/155061942-6a7afe79-0afe-46e5-82cb-ebb92e0f63ab.jpeg)

**Comment by smr547** [comment]
Hi Chris (@Christopher-w-green)

Could you please take some photos of the window frames as the work proceeds?  As you mentioned to me yesterday, the SeaSpray guys have undertaken to (for each of our windows):

* tape the area around the window
* sand back to clean metal
* apply metal primer
* apply two part paint (black)

This should provide a finish (and protection) for many years to come.

I've asked Alexis to give us a price estimate on all this work as it was not part of my original budget. I've noticed that the labour involved with each window is significant and we have at least 8 of them.  

Some photos of the process might help the Committee understand the costs involved. To my way of thinking, the windows are deteriorating rapidly in the salty environment and we will be up for a much larger expense if we have to replace the frames. The option of a cheap spray paint is not worth considering giving the preparation time required.

kind regards
Steven

**Comment by Christopher-w-green** [comment]
Ok. See what I can do. Most of the windows are completely taped up now for
the antifoul spray.

I dropped in to see Alexis and Chris on my way out this morning. Chris
explained a bit about the process. He said one of the issues with aluminium
is that nothing sticks to it. Once you cut back the metal you need to get
the primer onto it before it can oxidize and then there are timing windows
for each of the coats of paint. That's why they haven't started work on the
frames on the deck level yet. So hopefully  I can get some "before" shots
of the windows up the top. Waiting for the next bus back th boatworks now,
but it's about an hour away.

**Comment by smr547** [comment]
Alexis has advised that the quote for repairing the window frames with two part epoxy paint  is $1000.

**Comment by smr547** [comment]
Topside portholes stripped and repainted  by SeaSpray 12/11/22 -- there was not enough time to complete the work so the deck portholes have not been done.
Material and paint left on board for CORC crew to complete the work
@Christopher-w-green knows more 
Move to working bee

@delcosta and @peterottesen will be interested

**Comment by smr547** [comment]
@Christopher-w-green has done a great job of completing the painting of the coach-house window frames -- a very professional finish. 

Closing this issue but retaining on the list of routine maintenance
