### ISSUE TITLE
Antifoul to hull

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#568]
- [ ] Pressure wash hull
- [ ] Repair any damage to hull surface
- [ ] sand back
- [ ] two coats of Antifoul  [Altex No.5 Black](https://drive.google.com/file/d/1XrHfh0dVV__pb92Bi7jyh6jU3SxhPeJv/view?)
- [ ] No antifoul on saildrive leg
- [ ] Avoid rudder bearings

**Comment by smr547** [comment]
work done by Seaspray marine. Reschedule for next year and close this issue
[Invoice INV-04099 (1).pdf attached](https://github.com/CanberraOceanRacingClub/namadgi3/files/10107952/Invoice.INV-04099.1.pdf)

**Comment by smr547** [comment]
Due to be done at boatworks -- Sandblast may be necessary

**Comment by smr547** [comment]
Here is the quote from Bradford Marine, Coomera to antifoul the hull

* Antifoul only = $7000
* Add sandblast = $7000
* Total = $14,000

The sandblast was recommended last year by SeaSpray marine when they noticed a large patch of antifoul delaminating from the hull - possibly due to poor application of a previous coat. 

[Quote QU1113.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/12808932/Quote.QU1113.pdf)

#quote=$14000

@mgrybaitis @peterottesen @pcbaston @Christopher-w-green @delcosta @DimitD @pjwain

**Comment by delcosta** [comment]
Thanks Steven
Turns out affordable are 'Less Affordable'
You got the job done in best time and that is the most important thing .
Allister, see invoice by below link

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603
______________________________________________________________________________________
IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail

**Comment by smr547** [comment]
Work completed by Affordable

**Comment by smr547** [comment]
Two invoices from Affordable Antifoul:

* [INV00003257.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/13591122/INV00003257.pdf) -- deposit paid by SMR via Credit Card
* [INV00003266.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/13591121/INV00003266.pdf) -- Balance on completion of work paid directly by CORC

**Comment by smr547** [comment]
[Jotun Sea Victor 50](https://marinetradesupplies.com.au/product/seavictor-50-black-10l-24/) Antifoul was used
