### ISSUE TITLE
Stowage of angle grinder

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#664]
In his Cat 1 audit report dated Nov 2022 @peterottesen recommended:

>The battery powered angle grinder and drill to be stored below decks and the condition of the battery checked regularly.  They are at significant risk of failure with being stowed in the aft deck locker.

Peter is mainly concerned about corrosion. This bag should be stored

- [ ] In a position close to a power point so that batteries may be recharged
- [ ] NOT under the floor boards as N3 presently has a wet bilge

@Christopher-w-green could you please give this consideration while preparing for you repositioning passage? Please let @PSARN know of the changed position so the stowage plan #31 can be updated.

**Comment by PSARN** [comment]
The Grinder and Drill have been moved to location 65 (STB seat locker middle)


From: Steven Ring ***@***.***>
Reply to: CanberraOceanRacingClub/namadgi3 ***@***.***>
Date: Sunday, 1 January 2023 at 04:46
To: CanberraOceanRacingClub/namadgi3 ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: [CanberraOceanRacingClub/namadgi3] Stowage of angle grinder (Issue #664)


In his Cat 1 audit report dated Nov 2022 @peterottesen<https://github.com/peterottesen> recommended:

The battery powered angle grinder and drill to be stored below decks and the condition of the battery checked regularly. They are at significant risk of failure with being stowed in the aft deck locker.

Peter is mainly concerned about corrosion. This bag should be stored

  *   In a position close to a power point so that batteries may be recharged
  *   NOT under the floor boards as N3 presently has a wet bilge

@Christopher-w-green<https://github.com/Christopher-w-green> could you please give this consideration while preparing for you repositioning passage? Please let @PSARN<https://github.com/PSARN> know of the changed position so the stowage plan #31<https://github.com/CanberraOceanRacingClub/namadgi3/issues/31> can be updated.

**Comment by PSARN** [comment]
The Grinder and Drill have been moved to location 65 (STB seat locker middle) and recorded in MLA @smr

**Comment by smr547** [comment]
closing this issue
