### ISSUE TITLE
Fuel bladder - leaking around refill tube

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#678]
From the base of the refill tube.

@mrmrmartin has retighted the nuts after applying locktite

@peterottesen will be interested

**Comment by pcbaston** [comment]
The fuel bladdr will not be used again until May - the next ocean crossing. Is this still an issue??

**Comment by pcbaston** [comment]
Michael martin reported that the fill tube (leaking) was glued using approved fuel container glue (white sticky stuff) and the securing screws tightened with Loctite applied.  
Believe this could have been a manufacturing problem since this was the first use. Should be no further issues.

Issue CLOSED.

**Comment by pcbaston** [comment]
Allister reported 4May23:
"The fuel bladder leak has been fixed by the following:
Undoing the fitting, which was only hand tight for my little office hands… I note there is a section seal about 6 mm from the end of the threads and I am guessing it was not tightened to this point previously.
Cleaning the thread and fitting. I suspect it may have been ‘sealed’ with B5200 which dries in moisture. It was still fairly tacky. Acetone is a solvent for B5200, so I cleaned the threads with acetone.
Applied Bondloc B243 which is medium strength (Loctite like) and oil tolerant.
Reattached the fitting and tightened it with tools as tight as I dared so as not to break or strip the fitting.
Pressure testing on the bladder to come."
