### ISSUE TITLE
Turn off gas at bottle sign or sticker

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#69]
Buy one
timing: July

**Comment by DeeTaylor87** [comment]
Note Cat One Requirements

3.17.4(a) | A sign reading   "REMEMBER Turn Off Gas At Bottle" shall be displayed near any gas   appliance.
-- | --
(b) | Boats   equipped with gas systems using permanent flames, e.g. a pilot light, shall   be fitted with a combustible gas detection system.
3.17.5 (a) | Disposable   gas cooking canisters used inside the boat must be no more than 225 gram   capacity.
3.17.6 | Gas   bottles, cylinders and reserve canisters shall be contained in separate   ventilated and self-draining compartments where vapour can only escape   overboard.

**Comment by DeeTaylor87** [comment]
Other signage required by boat includes the following issues:
159 – Easy to read On Off labels needed on all bow thruster and engine cock because the current 0 I labels are too small to read – check on the boat how many and what size we want
158 – Rego and call sign next to radio and in cockpit  
136 – Relabel clutches in cockpit - Two up-haul should be labelled main halyard and topping lift, main->main sheet
131 – Sticker to show the position of fire extinguisher in cockpit
117- label the anchor circuit breaker behind cushion below switch panel
116 - Diagram of switch matrix needs to be laminated and placed near switch panel

**Comment by smr547** [comment]
Thanks for doing these Dee -- I've assigned each to you. You should now be able to see a list of all issues assigned to you. Cheers
Steven

**Comment by DeeTaylor87** [comment]
![image](https://user-images.githubusercontent.com/30706096/29061001-66c488a0-7c5f-11e7-9822-421c6398248a.png)
I picked up this today. Not sure if it should be mounted yet though - do we need to figure out what we are doing with the extension to the gas supply first?

**Comment by DeeTaylor87** [comment]
We have put it in the galley above the stove.  The rules say about it being near all gas appliances, but if we were racing, we would not have the BBQ on board, so it does not need a sign there.
