### ISSUE TITLE
House Batteries - low

### ISSUE THREAD

**Issue by mgrybaitis** [CanberraOceanRacingClub/namadgi3#690]
Mark Miller reported to me today 9/3/2023 that the House Batteries were not charging above 55% and that they have been down as low as 30%. He will be on power today (as back in the marina) - and it will be interesting to see if they fully charge. If they don't - than they will probably need to be replaced.

@smr547 @pcbaston will be interested

**Comment by pcbaston** [comment]
If these batteries need replacing, I suspect we have a charging issue. Batteries should never be allowed to drop below 55% or they may not recover. Replacing batteries is expensive. Note relationship to Bow Thruster issue due to a failed battery. All were working fine up to NZ4 booking suggesting possible common failure point (charging system).  Someone may need to sit in port while services investigate.

**Comment by smr547** [comment]
I don't think the batteries need replacing at this stage. I spoke with Mark Miller yesterday, he said that they had been using the motor for only about an hour a day while in "relaxed cruising mode". This is insufficient to keep the batteries fully charged and they will, over a few day, lose charge capacity. @pjwain had advised mark to run the main engine for about 3 hours per day to maintain a full charge -- I think we'd all agree with that advice.

Mark is in port and is charging the batteries via shore power. We should see the batteries return to a full charge state -- I'll check with Mark today.

This begs the question, should we use the Honda Genset for casual charging while cruising, rather than "emergency use only"?  Use of the genset would save hours on the Volvo diesel and extend the period between services. If we go this way I'd recommend the installation of a second 40A battery charger (bringing our charger capacity to 80A -- or 1.2kW) to better match the output capacity of the genset (2.2kW) -- this will also half the charging time.

It would also be prudent to look forward to the replacement of the house batteries as these generally have a limited lifespan of about 5 to 7 years. I'll raise a GitHub issue for this.

Suggest we close this issue once Mark has reported a normal charge state later today.

**Comment by pcbaston** [comment]
Michelle and Allister both reported no issues with batteries on completion of their booking. Issue CLOSED.
