### ISSUE TITLE
Renew house batteries?

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#692]
Is it time to start planning for the renewal of the house batteries?

Lead/acid AGM batteries (as currently installed) generally have a lifespan of about 5 years.  @pjwain, do you remember if and when our house batteries were last renewed?

We MUST avoid the inconvenience and high cost of having to replace failed batteries in a remote location (or failure while at sea).

Perhaps our next annual maintenance stopover at The Boat Works, Qld (Nov this year or next year??) would be the ideal time to do this?

I'd recommend Lithium battery technology as we will be able to reduce our battery weight (and starboard side list) significantly. Lithium batteries can be discharged to about 5% of installed capacity whereas our current AGM is limited to 55%!

I think we have about 600Ah installed capacity at the moment (this needs to be checked). 

If we were to replace with 500Ah of Lithium the cost would be about #BudgetDollars=5000 including batteries, installation, upgrades to charging and monitoring system.

For committee discussion

@pjwain @pcbaston @delcosta @Bill-Russo @mgrybaitis @mrmrmartin @peterottesen @DimitD 
refers #690

**Comment by mrmrmartin** [comment]
Hi Steven

I remember checking the batteries as I was unsure if they were the originals or not.

They were not the originals and I guess because we have had the  boat for 5+ years they would have to be a few years old
Peter Wain may remember when they were replaced given he would have paid the bill.

cheers

From: Steven Ring ***@***.***>
Sent: Friday, 10 March 2023 9:19 AM
To: CanberraOceanRacingClub/namadgi3 ***@***.***>
Cc: mrmrmartin ***@***.***>; Mention ***@***.***>
Subject: [CanberraOceanRacingClub/namadgi3] Renew house batteries? (Issue #692)


Is it time to start planning for the renewal of the house batteries?

Lead/acid AGM batteries (as currently installed) generally have a lifespan of about 5 years. @pjwain<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpjwain&data=05%7C01%7C%7C2ab6d12d22794eff946908db20ec464c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139971400030811%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=idoeSgRhWPqPavdqWHqKTTsMgKXKEgisR4dR9J0%2FL1M%3D&reserved=0>, do you remember if and when our house batteries were last renewed?

We MUST avoid the inconvenience and high cost of having to replace failed batteries in a remote location (or failure while at sea).

Perhaps our next annual maintenance stopover at The Boat Works, Qld (Nov this year or next year??) would be the ideal time to do this?

I'd recommend Lithium battery technology as we will be able to reduce our battery weight (and starboard side list) significantly. Lithium batteries can be discharged to about 5% of installed capacity whereas our current AGM is limited to 55%!

I think we have about 600Ah installed capacity at the moment (this needs to be checked).

If we were to replace with 500Ah of Lithium the cost would be about #BudgetDollars=5000 including batteries, installation, upgrades to charging and monitoring system.

For committee discussion

@pjwain<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpjwain&data=05%7C01%7C%7C2ab6d12d22794eff946908db20ec464c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139971400030811%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=idoeSgRhWPqPavdqWHqKTTsMgKXKEgisR4dR9J0%2FL1M%3D&reserved=0> @pcbaston<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpcbaston&data=05%7C01%7C%7C2ab6d12d22794eff946908db20ec464c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139971400030811%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pVW9mQqRoIbXMqguyB7KQ8bOUSbwnoMUDTupggKG0lg%3D&reserved=0> @delcosta<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdelcosta&data=05%7C01%7C%7C2ab6d12d22794eff946908db20ec464c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139971400030811%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=691cteS2mwd%2B6ZuJEzd3dUkyLAXzskVg9zlRej%2FLBlA%3D&reserved=0> @Bill-Russo<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBill-Russo&data=05%7C01%7C%7C2ab6d12d22794eff946908db20ec464c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139971400187050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3nizj9zT7zxr8YevrOlZN4w9m5xFBiiUW6nGiA3Zwjs%3D&reserved=0> @mgrybaitis<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmgrybaitis&data=05%7C01%7C%7C2ab6d12d22794eff946908db20ec464c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139971400187050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=h2c5ZKPwtnq6jgR8W9%2FoNJ%2Fl0JBUBUTA%2Fgl3PGbIOfE%3D&reserved=0> @mrmrmartin<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmrmrmartin&data=05%7C01%7C%7C2ab6d12d22794eff946908db20ec464c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139971400187050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sTdiJWl5spNt6%2BxdQOzvFw9VrHMfFWOgfeMgWp8AskU%3D&reserved=0> @peterottesen<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpeterottesen&data=05%7C01%7C%7C2ab6d12d22794eff946908db20ec464c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139971400187050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KbGZcBHoqRWtYS2rRTUuuIjZDv9JDEau38c7OyU98RE%3D&reserved=0> @DimitD<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDimitD&data=05%7C01%7C%7C2ab6d12d22794eff946908db20ec464c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139971400187050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TQdUvl9iJsjyRi07Pb8N6YxMpbwjjMus76g8dEDAI%2FM%3D&reserved=0>
refers #690<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCanberraOceanRacingClub%2Fnamadgi3%2Fissues%2F690&data=05%7C01%7C%7C2ab6d12d22794eff946908db20ec464c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139971400187050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tg0lrNY4lt%2BhCWBpittf8n7WJTQvggJjuKJPDJWK22Y%3D&reserved=0>

-

**Comment by pjwain** [comment]
Hi Steve, I have a record of us getting 5 new batteries from Anderson
Marine in May 2019, which makes them getting on for 4 years old. I may have
a hard copy of the receipt back in Aus if you want it. I'll be back in a
couple of days. Regards, Peter.

**Comment by pjwain** [comment]
Hi Steve,
Further to my previous email, I'm attaching for your information the
invoice for the battery replacement in May 2019. Note that it covers other
electrical things as well, including the HF radio supply &  installation,
bow thruster check, and Iridium Go installation.
All the best, Peter.

**Comment by pcbaston** [comment]
House Battery issue has been closed. Issue was lack of charging and allowing battery to discharge below 55%. This constraint should be known by all skipper's (Skippers Notes)?
Based on no problem, NFA required 
Issue CLOSED.
