### ISSUE TITLE
Genoa winch on port side is failing

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#757]
BEWARE -- the winch ratchet recently failed allowing the working sheet to rotate the winch drum in the wrong direction -- the handle in the winch spun out of control.

Users should beware that this can cause serious injury.

The winch needs to be serviced urgently to restore it to normal operation.  Reopening #382

**Comment by SamMcDonald2538** [comment]
Hey Steve,
is there a record of the last maintenance carried out on the winches? Lewmar recommend annual services are carried out. I will contact the local distributor to enquire about service kits, if they are due or overdue, we should do all of them.

**Comment by smr547** [comment]
Hi Sam (@SamMcDonald2538)

The last strip-down and service was done by @GarthBrice in Opua in early 2023 -- before the NZ to Fiji Passage -- see issue #382 for history.

I suspect that this problem is a sticky or failed spring in a ratchet mechanism. 

It  deserves urgent attention. There is a risk that the clutch will not "lock" after tension has been put on the genoa sheet. The result is a winch handle spinning at high speed. I got whacked by the handle and it's not pleasant.

I'm happy to do the servicing on 29 Jan if @pjwain and @pcbaston (the skippers before me) are happy to put up with the problem (i.e. Don't use that winch)

**Comment by GarthBrice** [comment]
StevenI agree with your assessment of the problem causing the winch failure. Given that one winch has failed I would recommend that all the other winches need to have a full service. It would seem that they have done a lot of work since the last service in Opua. Kind RegardsGarthSent from my iPhoneOn 11 Jan 2024, at 07:31, Steven Ring ***@***.***> wrote:﻿
Hi Sam ***@***.***)
The last strip-down and service was done by @GarthBrice in Opua in early 2023 -- before the NZ to Fiji Passage -- see issue #382 for history.
I suspect that this problem is a sticky or failed spring in a ratchet mechanism.
It  deserves urgent attention. There is a risk that the clutch will not "lock" after tension has been put on the genoa sheet. The result is a winch handle spinning at high speed. I got whacked by the handle and it's not pleasant.
I'm happy to do the servicing on 29 Jan if @pjwain and @pcbaston (the skippers before me) are happy to put up with the problem (i.e. Don't use that winch)

**Comment by pcbaston** [comment]
I could look at it but I've never done that before. Chris green will be
with me. If it's a spring or pawl, are there spares held?

Paul Baston

**Comment by GarthBrice** [comment]
PaulYes there are spares onboard In the box with all the winch servicing gear.Chris knows how to strip the winch down and replace the pawl or spring. Kind RegardsGarth Sent from my iPhoneOn 11 Jan 2024, at 17:31, Paul Baston ***@***.***> wrote:﻿
I could look at it but I've never done that before. Chris green will be

with me. If it's a spring or pawl, are there spares held?



Paul Baston

**Comment by pcbaston** [comment]
👍
Regards,

*Paul Baston*

**Comment by pcbaston** [comment]
All,  we didn't strip the winch as, quite frankly, we forgot to. It worked flawless for us for 4 days sailing, including fully loaded in 20 knots wind (where yacht was doing 8 knots upwind).

**Comment by smr547** [comment]
Agreed, worked flawlessly for us too. Closing this issue noting that the winches will be serviced at the next working bee (see #382 )

**Comment by smr547** [comment]
Unfortunately the winch failed to lock again last night. Will need to be investigated.

**Comment by smr547** [comment]
Pauls cleaned and re-oiled by @Christopher-w-green at Coffs Harbour -- all working well.

**Comment by GarthBrice** [comment]
StevenI assume that it is the same winch that failed last time.Michelle said she had completely stripped the winch down, cleaned the pawls and reassembled the winch. Patrice and I did not repeat the process on that winch but we did service all the other winches. We did find a lot of corrosion in the other winches from salt water ingress which we removed with the brass brush. Perhaps that may be the problem?Kind RegardsGarth Sent from my iPadOn 2 May 2024, at 1:11 AM, Steven Ring ***@***.***> wrote:﻿
Unfortunately the winch failed to lock again last night. Will need to be investigated.

**Comment by Christopher-w-green** [comment]
Seems like only one pair of Paul's was cleaned. The other set of cogs and
Paul's was clagged

**Comment by pcbaston** [comment]
Pawls, not Paul's
Regards,

*Paul Baston*

**Comment by Christopher-w-green** [comment]
Thanks Pawl. Autocorrelation strikes again.
