### ISSUE TITLE
RIB deck brackets

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#77]

**Comment by delcosta** [comment]
I have a picture of a system I took during a delivery some time ago. I will search for that photo.
We need to add enough fixing points that will secure the RIB that can also be useful in our sailing.

**Comment by DeeTaylor87** [comment]
The brackets Sam is talking about are kind of padded V shaped cradle that the dinghy sits into.  That would mean that the dinghy would sit 'right side up' on the deck.  We would have to leave the bung out so that the dinghy could drain in wet weather.  It would enable us to open and close the hatches.

**Comment by DeeTaylor87** [comment]
https://mail.google.com/mail/u/0/?ui=2&ik=92c7ec154a&view=fimg&th=15e1dda006c1ffc9&attid=0.1&disp=inline&safe=1&attbid=ANGjdJ_1Dy6BxCgNGPYIKxrU9zlABD1zxM2cgk1E8COjTiziHVXx3nR8V6njkh7-OvSoGyfJxHeRnRyMSa048LsGE0Z5fycn8C_FOvoNpcoECSW0I5R26ZMgFIVtdVs&sz=w1600&ats=1503739596488&rm=15e1dda006c1ffc9&zw

**Comment by smr547** [comment]
Foam cradle to be cut to size at Clark Rubber
D brackets to be fitted by shipwrights at Quays
We need to position the dinghy on the deck and determine the size of the cradles and the location of
D brackets on the deck -- another working bee required?
@DeeTaylor87 do you have measurement of Dinghy and photos of the Elan deck fittings

**Comment by DeeTaylor87** [comment]
Yes - just waiting for them to upload via email. Will have them shortly

**Comment by smr547** [comment]
Excellent -- thank you!!

**Comment by DeeTaylor87** [comment]
Just in front of the Dodger on the Elan there were two D brackets. They were centred on the deck about 20cm apart.  Along the midline of the deck, 62.5cm in front of those brackets there was another D bracket.  Photo soon.

**Comment by smr547** [comment]
Remember item #77 is about the RIB / Dinghy -- not the liferaft :D

**Comment by DeeTaylor87** [comment]
Yes - my comments above relate to the Dinghy... :)  I do have extra measurements though.  The distance between the port and starboard D brackets on the sloping part of the deck is 150cm.  The distance between the port D bracket and the most forward D bracket (just behind the anchor) is 177cm.  Pictures to follow shortly

**Comment by DeeTaylor87** [comment]
The most forward D bracket:
![elan forward d clip](https://user-images.githubusercontent.com/30706096/29771919-7b1f8428-8c39-11e7-88a9-c28b3bebb7ab.jpg)
The mast D brackets
![elan mast d clips](https://user-images.githubusercontent.com/30706096/29771931-8a50dc8a-8c39-11e7-86f5-530bc354241f.jpg)
The starboard side sloping deck D bracket (look carefully to see this one!)
![elan side sloping d clips](https://user-images.githubusercontent.com/30706096/29771958-a2a781b2-8c39-11e7-82ee-89cd32305eda.jpg)

**Comment by DeeTaylor87** [comment]
Sam's cradle vision
![sam s cradle](https://user-images.githubusercontent.com/30706096/29796194-38601a1c-8c93-11e7-9669-31bac153243e.jpg)
@delcosta @smr547 @SRDunlop

**Comment by DeeTaylor87** [comment]
The BAVARIA currently only has three fixing points - one 16cm directly in front of the mast and then one each to port and starboard of that central point, just before the deck begins to slope away.  

The distance from the mast D bracket to the twin forward hatches is 100cm, the hatches are 57cm long and then the distance from the hatches to the start of the slope down towards the bow well is 65cm.  So we have just over 2.2m before the deck slopes down if our RIB is fixed over the hatches.  I think the cradle is designed to sit in the space between those twin hatches so that the curvature of the RIB hull would allow us to open the hatches a few centimetres even with the RIB tied in place.  I think the hatches hinge at the most forward side of the hatch, so it will be interesting to see if there is enough room still to open with the RIB tied in place.  Cross your fingers. 💃   Ahhh, it is the :D smiley keys which produces the image options!

**Comment by DeeTaylor87** [comment]
When you compare the foredeck distances on the elan with the distances on the Bavaria, we used over 3m of space between the clipping points on the Elan.  We have 2.2m of space before the slope down to the bow-well on the Bavaria. The length of the slope on the Bavaria is 45cm and then the distance to the Bow well is 85cm - an additional 1.3m if you  tie the RIB over the sloping section.  That means 3.5m between mast D Bracket and Bow Well on the Bavaria, as opposed to 3m between D brackets on the Elan.

**Comment by jphayden** [comment]
Rather than rush into this . We are proposing that for the trip to BB , we lash it down on the foredeck. There is the one padeye just fwd of the mast. and ropes can be lashed through the fwd cleat guides 
the Dinghy is currently at the Quays and maybe we could pop in there on departure ( also maybe refuel there etc as we have an account.
I am not sure whether we have found the paddles or not - any one know/

**Comment by smr547** [comment]
Closing this item -- historical
