### ISSUE TITLE
Saltwater sink faucet

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#86]
Do we need one?
estimate: $200

**Comment by DeeTaylor87** [comment]
Footpump available at RT Marine https://www.roadtechmarine.com.au/galley-foot-pump-flush-to-floor-type-tip-toe-pump/p/TCE015

We did use the saltwater pump in the galley on the other boat - was very helpful when you need to rinse dishes etc and don't want to use precious fresh water on long trips.

**Comment by DeeTaylor87** [comment]
Spoke to Lincoln the plumber at Quays about this option today. If we do this, he would bring seawater down from the inlet that feeds the port aft toilet down to the galley sink, running behind the cupboard. He would fit the pump in the storage bay just in front of the galley sink. It would be a little fiddly perhaps, but it is possible when we are ready.

**Comment by smr547** [comment]
Did he give a cost estimate?

**Comment by DeeTaylor87** [comment]
No - he wasn't prepared to talk price just yet. He deferred all question of cost to his boss Darren Skinner. He did seem quite reluctant at first because he was concerned about not messing up our lovely cabinets. Eventually agreed it was possible but not prepared to put a price on it until we are really serious about it.

**Comment by DeeTaylor87** [comment]
Quote provided by Q Services.

**Comment by smr547** [comment]
Closing this item -- historical
