### ISSUE TITLE
Earth strap cable and nut is loose on keel bolt

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#96]
who: CORC
timing: July

**Comment by DeeTaylor87** [comment]
Communication with Daniel from BME 28th August 
Hi Daniel, Jack Hayden CORC here. The matters we wanted to address are: Light in the engine bay, provision of fuse kit, check the battery monitor, check the electrical cable on the forward keel bolt, Isolation transformer is noisy, Provision of 12V and 240V circuit diagrams

**Comment by DeeTaylor87** [comment]
Chris from BME tightened it and put a washer or two on it so that it won't work itself loose again.  He said it can be sprayed with WD40 if we like, to help prevent corrosion (the lubricant doesn't do anything electrical for it, it is just there to slow down the corrosive impact of air and salt etc).
