### ISSUE TITLE
Metal or plastic cover for companionway door step

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#99]
It will get very damaged. It's also very sharp

**Comment by DeeTaylor87** [comment]
http://www.plastimake.com/about

Would this product work?

**Comment by DeeTaylor87** [comment]
Leaving a piece of magic grip seems to work ok although it isn't a particularly pretty option. Clark Rubber and Bunnings didn't seem to have anything that would work any better.  Bunnings does have thick sheets of rubber plastic that would mould to the step, but it would probably be very slippery when wet and present a safety hazard.  I think the trimmers at Quays might have a few more ideas though, so I'll ask them next time I'm down there.  Perhaps a weathermax cover might do the trick,

**Comment by DeeTaylor87** [comment]
Note that the issue is not that the door step is very sharp!!!  LOL..  Someone suggested that if we use a metal strip as a cover, it may present a sharp hazard at the top of the stairs. A person may catch their foot in it or it may come loose and trip them going down the companionway stairs.  I think it is a legitimate concern - I have hurt my ankle quite nastily by catching it on our silly metal flyscreen and I would not like to repeat that. We need to be cautious and prudent using metal as a surface protector here.

**Comment by DaveHolt** [comment]
Two people skinned their shins on the sharp timber outer edge over the last couple of days. Maybe we could use a router or sander to roll the edge a little. The teak is pretty hard and seems to be holding up quite well, better than the shins!

**Comment by DeeTaylor87** [comment]
Sounds good to me. I haven't experienced a sharpness to the timber - but if others find it an issue, I say "sand away!"
